name: CI
on:
    push:
        branches: ["main"]
    pull_request:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  lfs: true
                  fetch-depth: 0

            - name: Configuración Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Instalación de dependencias
              run: pip install -r requirements.txt

            - name: Ejecución de tests
              env:
                  PYTHONPATH: .
              run: pytest
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  lfs: true
                  fetch-depth: 0
            - name: Despliegue en Hugging Face
              run: |
                  git remote add hf https://lm-jim:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/lm-jim/mdl-mlops
                  git push hf main --force
